### ISSUE TITLE
Runtime Interrupted errors.

### ISSUE THREAD

**Issue by yangboz** [OpenModelica/jupyter-openmodelica#11] opened 2017-11-27 15:14 UTC
After "docker run -p 8888:8888  smartkit/jupyter-openmodelica" , some error thrown: 

[I 15:07:41.383 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 15:07:41.772 NotebookApp] Serving notebooks from local directory: /app
[I 15:07:41.773 NotebookApp] 0 active kernels
[I 15:07:41.773 NotebookApp] The Jupyter Notebook is running at:
[I 15:07:41.773 NotebookApp] http://0.0.0.0:8888/?token=14651ec082339e69f25cf94e5f1878df28f8e4d3325cfe53
[I 15:07:41.773 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 15:07:41.774 NotebookApp] No web browser found: could not locate runnable browser.
[C 15:07:41.774 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://0.0.0.0:8888/?token=14651ec082339e69f25cf94e5f1878df28f8e4d3325cfe53
^C[I 15:08:06.224 NotebookApp] Interrupted...
[I 15:08:06.225 NotebookApp] Shutting down 0 kernels
smartkit@localhost:~/git/jupyter-openmodelica$ docker run -p 8888:8888  smartkit/jupyter-openmodelica
[I 15:08:23.193 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 15:08:23.583 NotebookApp] Serving notebooks from local directory: /app
[I 15:08:23.583 NotebookApp] 0 active kernels
[I 15:08:23.583 NotebookApp] The Jupyter Notebook is running at:
[I 15:08:23.584 NotebookApp] http://0.0.0.0:8888/?token=2338da0f0e9447049f718506226dfeae85c21983d17ce1a6
[I 15:08:23.584 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 15:08:23.586 NotebookApp] No web browser found: could not locate runnable browser.
[C 15:08:23.587 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://0.0.0.0:8888/?token=2338da0f0e9447049f718506226dfeae85c21983d17ce1a6
[I 15:08:35.889 NotebookApp] 302 GET /?token=2338da0f0e9447049f718506226dfeae85c21983d17ce1a6 (172.17.0.1) 0.86ms
[I 15:08:43.399 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[W 15:08:43.403 NotebookApp] Notebook OpenModelica.ipynb is not trusted
[W 15:08:43.450 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20171127150823 (172.17.0.1) 14.66ms referer=http://0.0.0.0:8888/notebooks/OpenModelica.ipynb
[I 15:08:43.911 NotebookApp] Kernel started: 820ab535-a82a-42eb-a25c-4d4395c6c59b
[W 15:08:43.922 NotebookApp] 404 GET /static/components/codemirror/mode/openmodelica/openmodelica.js?v=20171127150823 (172.17.0.1) 6.02ms referer=http://0.0.0.0:8888/notebooks/OpenModelica.ipynb
2017-11-27 15:08:47,189 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Error: You are trying to run OpenModelica as a server using the root user.
This is a very bad idea:
* The socket interface does not authenticate the user.
* OpenModelica allows execution of arbitrary commands.
Execution failed!

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/openmodelica_kernel/__main__.py", line 43, in <module>
    IPKernelApp.launch_instance(kernel_class=OpenModelicaKernel)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/app/openmodelica_kernel/kernel.py", line 125, in __init__
    self.omc=OMCSessionZMQ()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 502, in __init__
    self._connect_to_omc()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 528, in _connect_to_omc
    raise Exception
Exception
name 'reload' is not defined
[I 15:08:49.909 NotebookApp] KernelRestarter: restarting kernel (1/5)
2017-11-27 15:08:53,095 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Error: You are trying to run OpenModelica as a server using the root user.
This is a very bad idea:
* The socket interface does not authenticate the user.
* OpenModelica allows execution of arbitrary commands.
Execution failed!

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/openmodelica_kernel/__main__.py", line 43, in <module>
    IPKernelApp.launch_instance(kernel_class=OpenModelicaKernel)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/app/openmodelica_kernel/kernel.py", line 125, in __init__
    self.omc=OMCSessionZMQ()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 502, in __init__
    self._connect_to_omc()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 528, in _connect_to_omc
    raise Exception
Exception
name 'reload' is not defined
[W 15:08:53.948 NotebookApp] Timeout waiting for kernel_info reply from 820ab535-a82a-42eb-a25c-4d4395c6c59b
[I 15:08:55.917 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 820ab535-a82a-42eb-a25c-4d4395c6c59b restarted
2017-11-27 15:08:59,151 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Error: You are trying to run OpenModelica as a server using the root user.
This is a very bad idea:
* The socket interface does not authenticate the user.
* OpenModelica allows execution of arbitrary commands.
Execution failed!

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/openmodelica_kernel/__main__.py", line 43, in <module>
    IPKernelApp.launch_instance(kernel_class=OpenModelicaKernel)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/app/openmodelica_kernel/kernel.py", line 125, in __init__
    self.omc=OMCSessionZMQ()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 502, in __init__
    self._connect_to_omc()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 528, in _connect_to_omc
    raise Exception
Exception
name 'reload' is not defined
[I 15:09:01.929 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 820ab535-a82a-42eb-a25c-4d4395c6c59b restarted
2017-11-27 15:09:05,138 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Error: You are trying to run OpenModelica as a server using the root user.
This is a very bad idea:
* The socket interface does not authenticate the user.
* OpenModelica allows execution of arbitrary commands.
Execution failed!

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/openmodelica_kernel/__main__.py", line 43, in <module>
    IPKernelApp.launch_instance(kernel_class=OpenModelicaKernel)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/app/openmodelica_kernel/kernel.py", line 125, in __init__
    self.omc=OMCSessionZMQ()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 502, in __init__
    self._connect_to_omc()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 528, in _connect_to_omc
    raise Exception
Exception
name 'reload' is not defined
[I 15:09:07.940 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 820ab535-a82a-42eb-a25c-4d4395c6c59b restarted
2017-11-27 15:09:11,188 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Error: You are trying to run OpenModelica as a server using the root user.
This is a very bad idea:
* The socket interface does not authenticate the user.
* OpenModelica allows execution of arbitrary commands.
Execution failed!

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/openmodelica_kernel/__main__.py", line 43, in <module>
    IPKernelApp.launch_instance(kernel_class=OpenModelicaKernel)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/app/openmodelica_kernel/kernel.py", line 125, in __init__
    self.omc=OMCSessionZMQ()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 502, in __init__
    self._connect_to_omc()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 528, in _connect_to_omc
    raise Exception
Exception
name 'reload' is not defined
[I 15:09:13.953 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 820ab535-a82a-42eb-a25c-4d4395c6c59b restarted
2017-11-27 15:09:17,144 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Error: You are trying to run OpenModelica as a server using the root user.
This is a very bad idea:
* The socket interface does not authenticate the user.
* OpenModelica allows execution of arbitrary commands.
Execution failed!

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/openmodelica_kernel/__main__.py", line 43, in <module>
    IPKernelApp.launch_instance(kernel_class=OpenModelicaKernel)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/app/openmodelica_kernel/kernel.py", line 125, in __init__
    self.omc=OMCSessionZMQ()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 502, in __init__
    self._connect_to_omc()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 528, in _connect_to_omc
    raise Exception
Exception
[I 15:09:19.963 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 820ab535-a82a-42eb-a25c-4d4395c6c59b restarted
2017-11-27 15:09:23,179 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Error: You are trying to run OpenModelica as a server using the root user.
This is a very bad idea:
* The socket interface does not authenticate the user.
* OpenModelica allows execution of arbitrary commands.
Execution failed!

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/openmodelica_kernel/__main__.py", line 43, in <module>
    IPKernelApp.launch_instance(kernel_class=OpenModelicaKernel)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/app/openmodelica_kernel/kernel.py", line 125, in __init__
    self.omc=OMCSessionZMQ()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 502, in __init__
    self._connect_to_omc()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 528, in _connect_to_omc
    raise Exception
Exception
name 'reload' is not defined
[I 15:09:25.974 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 820ab535-a82a-42eb-a25c-4d4395c6c59b restarted
2017-11-27 15:09:29,400 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Error: You are trying to run OpenModelica as a server using the root user.
This is a very bad idea:
* The socket interface does not authenticate the user.
* OpenModelica allows execution of arbitrary commands.
Execution failed!

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/openmodelica_kernel/__main__.py", line 43, in <module>
    IPKernelApp.launch_instance(kernel_class=OpenModelicaKernel)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/app/openmodelica_kernel/kernel.py", line 125, in __init__
    self.omc=OMCSessionZMQ()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 502, in __init__
    self._connect_to_omc()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 528, in _connect_to_omc
    raise Exception
Exception
name 'reload' is not defined
[I 15:09:31.989 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 820ab535-a82a-42eb-a25c-4d4395c6c59b restarted
2017-11-27 15:09:35,217 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Error: You are trying to run OpenModelica as a server using the root user.
This is a very bad idea:
* The socket interface does not authenticate the user.
* OpenModelica allows execution of arbitrary commands.
Execution failed!

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/openmodelica_kernel/__main__.py", line 43, in <module>
    IPKernelApp.launch_instance(kernel_class=OpenModelicaKernel)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/app/openmodelica_kernel/kernel.py", line 125, in __init__
    self.omc=OMCSessionZMQ()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 502, in __init__
    self._connect_to_omc()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 528, in _connect_to_omc
    raise Exception
Exception
[I 15:09:38.000 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 820ab535-a82a-42eb-a25c-4d4395c6c59b restarted
2017-11-27 15:09:41,249 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Error: You are trying to run OpenModelica as a server using the root user.
This is a very bad idea:
* The socket interface does not authenticate the user.
* OpenModelica allows execution of arbitrary commands.
Execution failed!

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/openmodelica_kernel/__main__.py", line 43, in <module>
    IPKernelApp.launch_instance(kernel_class=OpenModelicaKernel)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/app/openmodelica_kernel/kernel.py", line 125, in __init__
    self.omc=OMCSessionZMQ()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 502, in __init__
    self._connect_to_omc()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 528, in _connect_to_omc
    raise Exception
Exception
[I 15:09:44.015 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 820ab535-a82a-42eb-a25c-4d4395c6c59b restarted
2017-11-27 15:09:47,277 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Error: You are trying to run OpenModelica as a server using the root user.
This is a very bad idea:
* The socket interface does not authenticate the user.
* OpenModelica allows execution of arbitrary commands.
Execution failed!

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/openmodelica_kernel/__main__.py", line 43, in <module>
    IPKernelApp.launch_instance(kernel_class=OpenModelicaKernel)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/app/openmodelica_kernel/kernel.py", line 125, in __init__
    self.omc=OMCSessionZMQ()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 502, in __init__
    self._connect_to_omc()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 528, in _connect_to_omc
    raise Exception
Exception
[I 15:09:50.028 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 820ab535-a82a-42eb-a25c-4d4395c6c59b restarted
2017-11-27 15:09:53,232 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Error: You are trying to run OpenModelica as a server using the root user.
This is a very bad idea:
* The socket interface does not authenticate the user.
* OpenModelica allows execution of arbitrary commands.
Execution failed!

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/openmodelica_kernel/__main__.py", line 43, in <module>
    IPKernelApp.launch_instance(kernel_class=OpenModelicaKernel)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/app/openmodelica_kernel/kernel.py", line 125, in __init__
    self.omc=OMCSessionZMQ()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 502, in __init__
    self._connect_to_omc()
  File "/usr/local/lib/python3.4/dist-packages/OMPython/__init__.py", line 528, in _connect_to_omc
    raise Exception
Exception
[

**Comment by thorade** [comment] 2017-11-29 08:46
Your text would be much more readable if you marked the error messages as code:
https://guides.github.com/features/mastering-markdown/

**Comment by arun3688** [comment] 2017-12-08 13:01
@yangboz , The problem is due to openmodelica cannot be started as root server, I have added the dockerfile, Test it

**Comment by yangboz** [comment] 2017-12-09 14:17
@arun3688 Thanks for updating, but while using docker build, thrown errors as following:
Get:240 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe libhwloc-plugins amd64 1.8-1ubuntu1.14.04.1 [12.0 kB]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2_2.9.1+dfsg1-3ubuntu4.10_amd64.deb  404  Not Found [IP: 91.189.88.152 80]

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_3.13.0-135.184_amd64.deb  404  Not Found [IP: 91.189.88.149 80]

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/libpython2.7-minimal_2.7.6-8ubuntu0.3_amd64.deb  404  Not Found [IP: 91.189.88.162 80]

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/python2.7-minimal_2.7.6-8ubuntu0.3_amd64.deb  404  Not Found [IP: 91.189.88.162 80]

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/libpython2.7-stdlib_2.7.6-8ubuntu0.3_amd64.deb  404  Not Found [IP: 91.189.91.26 80]

E: Failed to fetch http://build.openmodelica.org/apt/pool/contrib-trusty/omplot_1.12.0-1_amd64.deb  Connection failed

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/python2.7_2.7.6-8ubuntu0.3_amd64.deb  404  Not Found [IP: 91.189.91.23 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 160 MB in 22min 9s (121 kB/s)
The command '/bin/sh -c apt-get install -y omc omlib-modelica-3.2.2' returned a non-zero code: 100

**Comment by arun3688** [comment] 2017-12-09 17:30
I think this is system related issue, may be you should do sudo apt-get clean and try it

**Comment by sjoelund** [comment] 2017-12-11 12:09
The security server removed the old packages and published new ones since the last time your image ran `apt-get update`; the dockerfile should probably include an update command.

**Comment by arun3688** [comment] 2017-12-11 12:19
The apt-get update is already on the top of the dockerfile,  "docker prune system" fixed the problem and now it is working fine for him, i should close this issue now

**Closed as completed** 2017-12-11 13:18 UTC
